### ISSUE TITLE
Is there a way to use this without a filesystem?

### ISSUE THREAD

**Issue by eterps** [salesking/json_schema_tools#29]
Say I wanted to instantiate a schema from the response of a request to a URL or a read from a tuple in a document store, cache or database.

It seems all examples use a `path` parameter to a filesystem.
Can't I instantiate a schema from a string (or array of strings) so that it can come from anywhere?

**Comment by eterps** [comment]
Ah, it seems possible with this construc (as documented in the READMEt:

```ruby
schema = SchemaTools::Reader.read :client, { ... }
```

**Comment by schorsch** [comment]
es, you can simply pass a schema hash, also see the comments for the read method: 
https://github.com/salesking/json_schema_tools/blob/master/lib/schema_tools/modules/read.rb#L35

Besides take a look at the Hash Module, depending on your use case. https://github.com/salesking/json_schema_tools/blob/master/lib/schema_tools/modules/hash.rb 
which also allows the usage of a  'dynamic' schema to convert an object into its schema version:

`
obj = Invoice.new(title: 'hello world', number:'4711')
obj_hash = SchemaTools::Hash.from_schema(obj, schema: { your schema definition as hash } )
 #   => { 'invoice' =>{'title'=>'hello world', 'number'=>'4711' } } 
`

Beware thought that above is be problematic with nested object properties e.g. invoice.line_items, as they cannot be found in the circular parsing calls to def from_schema.
