### ISSUE TITLE
Inquiry, schema version 2

### ISSUE THREAD

**Issue by dmil** [salesking/json_schema_tools#30]
Does this work on things formatted in 
http //json-schema.org/draft-02/schema#

as opposed to 
http //json-schema.org/draft-04/schema#

I'm having a little trouble implementing, just wondering if i'm wasting my time / if its not compatible with draft-02 of the schema. Thanks!

**Comment by schorsch** [comment]
Sorry, to tell you that i don't support version 2 as things have changed and i did not tried to handle the differences.
